name: Lint
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i markdownlint-cli
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: make lint
